# Generated by Django 3.1 on 2020-08-24 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('k_app003', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'verbose_name_plural': 'k_app003'},
        ),
    ]
