# Generated by Django 3.1 on 2020-09-02 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('k_app003', '0002_auto_20200824_1310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'verbose_name_plural': 'Diary'},
        ),
    ]
