# Generated by Django 3.1 on 2020-09-02 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('k_app003', '0003_auto_20200902_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'verbose_name_plural': 'katupro003'},
        ),
    ]
